-- ==========================================================
-- SQL SETUP SCRIPT FOR CT CHALLENGE (SUPABASE DATABASE)
-- ==========================================================
-- INSTRUCTIONS:
-- 1. Go to your Supabase Dashboard (https://supabase.com).
-- 2. Open your project.
-- 3. Click on "SQL Editor" on the left sidebar.
-- 4. Click "New Query" and paste this script.
-- 5. Click "Run" on the bottom right to execute and create the table.
-- ==========================================================

-- 1. Create the students progress table
CREATE TABLE IF NOT EXISTS public.students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name text NOT NULL,
    student_class text NOT NULL,
    student_number text NOT NULL,
    unlocked_levels jsonb DEFAULT '[1]'::jsonb NOT NULL,
    completed_levels jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Constraint to prevent duplicate students and allow UPSERT matching on Name, Class, and Number
    CONSTRAINT unique_student_record UNIQUE (student_name, student_class, student_number)
);

-- 2. Add an index to speed up student lookups and sorting for leaderboard
CREATE INDEX IF NOT EXISTS idx_students_lookup ON public.students (student_name, student_class, student_number);
CREATE INDEX IF NOT EXISTS idx_students_updated_at ON public.students (updated_at DESC);

-- 3. Enable Row Level Security (RLS) on the table
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for Anonymous Client Access
-- (Allows students to save and read data without requiring complex authentication)

-- Policy: Allow anyone (anon) to see the student list (for the Leaderboard / scoreboard)
CREATE POLICY "Allow public read access for scoreboard" 
ON public.students 
FOR SELECT 
TO anon 
USING (true);

-- Policy: Allow any student to register / insert their record
CREATE POLICY "Allow public insert for registration" 
ON public.students 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Policy: Allow any student to update their own level progress
CREATE POLICY "Allow public update for progress synchronization" 
ON public.students 
FOR UPDATE 
TO anon 
USING (true) 
WITH CHECK (true);
